### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by Globulopolis**
Fixed an old bug with notifications.
Change component templates. Removed unnecessary styles(it's now uses Joomla styles). Added responsiveness to comments list. Change some microicons in component template to fontawesome icons for improve usability.
Applied Joomla codestyle to install script.

### CODE REVIEW

**Comment by exstreme** [comment]
This branch has conflicts that must be resolved

**Review by exstreme — APPROVED** [review]

**Comment by exstreme** [comment]
image

**Comment by Globulopolis** [comment]
This is not an error.
I'm currently working on fixing bugs with component javascript when form is hidden.
Just switch comment form to `Show` in component settings.

**Comment by exstreme** [comment]
Ok, then will wait.
The new rights do not match the logic a bit. For example, captcha will always be displayed for superusers and this cannot be overridden. And the default values ​​should be convenient, and not configured every time.

**Comment by Globulopolis** [comment]
> The new rights do not match the logic a bit. For example, captcha will always be displayed for superusers and this cannot be overridden.

I forgot about it. Will fix ACL checking for super user in next PR.

> And the default values ​​should be convenient, and not configured every time.

That does it mean? Default settings after install? Or default settings for ACL?

PS!
> Super User 
>     Grants the user "super user" status. Users with this permission can do anything on the site. Only users with this permission can change Global Configuration settings (this screen). These permissions cannot be restricted. It is important to understand that, if a user is a member of a Super Admin group, any other permissions assigned to this user are irrelevant. The user can do any action on the site. However, Access Levels can still be assigned to control what this group sees on the site. (Obviously, a Super Admin user can change Access Levels if they want to, so Access Levels do not totally restrict what a Super Admin user can see.) 
https://docs.joomla.org/Special:MyLanguage/J3.x:Access_Control_List_Tutorial

**Comment by exstreme** [comment]
>That does it mean? Default settings after install? Or default settings for ACL?
And default settings and default ACL

**Comment by Globulopolis** [comment]
> And default settings and default ACL

Ok, will think how to set up default acl.

**Pull request merged**
