### PR TITLE
Add de-DE language for main component

### LINKED ISSUE #59: German translations
Hey guys,
I started to re-introduce german translation for this extension. Would you accept a PR?

### PR DESCRIPTION
**Pull request by ThomDietrich**
Closes #59

### CODE REVIEW

**Comment by exstreme** [comment]
Hello! Great work!
Will you translate files from backend, plugins, modules?

**Comment by ThomDietrich** [comment]
Can do. May I ask if you guys would be willing to use a system like crowdin to ease the work of translation? I've used it in multiple projects and it was a great help.

https://crowdin.com

Example: https://crowdin.com/project/openhab-core

I can help you set it up if you like.

**Comment by exstreme** [comment]
> Can do. May I ask if you guys would be willing to use a system like crowdin to ease the work of translation? I've used it in multiple projects and it was a great help. Translating manual is quite tedious and changes like in #61 are impossible to track across multiple translations without such a tool.
> 
> https://crowdin.com
> 
> Example: https://crowdin.com/project/openhab-core
> 
> I can help you set it up if you like.

https://crowdin.com/project/jcomments-4/content/files try it

**Comment by ThomDietrich** [comment]
Not allowed to access. My username is "thomdietrich"

**Comment by exstreme** [comment]
oh my bad, I didn't verify my email

**Comment by exstreme** [comment]
If you can help with mapping files, it would be great

**Comment by ThomDietrich** [comment]
Works as expected.
I uploaded all existing translations and updated a bunch of strings. Let's see if you can trigger the PR before I do any further translating.

**Comment by ThomDietrich** [comment]
And btw for you. If you want to upload your russian translations, that's easily done in the Content tab:

grafik

--> "Upload"

**Comment by exstreme** [comment]
Mappings are wrong, that's why I will replace manually files

**Pull request merged**
