### PR TITLE
Fixed error in update sql

### PR DESCRIPTION
**Pull request by Globulopolis**

### CODE REVIEW

**Comment by exstreme** [comment]
`checked_out_time` DATETIME NULL - may be convert all fields for same logic?
And how about default values for datetime fields?

**Comment by exstreme** [comment]
Please revert update-jcomments.xml, after merge it will be updating to wrong zip, I will update it after building new version

**Comment by Globulopolis** [comment]
> `checked_out_time` DATETIME NULL - may be convert all fields for same logic?
> And how about default values for datetime fields?

`checked_out_time` must be NULL value.

**Comment by exstreme** [comment]
> > `checked_out_time` DATETIME NULL - may be convert all fields for same logic?
> > And how about default values for datetime fields?
> 
> `checked_out_time` must be NULL value.
> 
> Default values is set when saving items.

It's horrible

**Comment by Globulopolis** [comment]
> > > `checked_out_time` DATETIME NULL - may be convert all fields for same logic?
> > > And how about default values for datetime fields?
> > 
> > `checked_out_time` must be NULL value.
> > 
> > Default values is set when saving items.
> 
> It's horrible 

This field used only for block item from editing by other user while editing. And storing value like 0123-56-78 90:12 for non-blocked item doesn't make sense.

**Pull request merged**
