### PR TITLE
Fixed #29

### LINKED ISSUE #29: Access rules not saved correctly in component settings.
How to reproduce:
Tune ACL via com_config, save. All working.
Just save settings in component. All ACL in Deny/Blocked state.

image
image
By registered

_Originally posted by @exstreme in https://github.com/exstreme/Jcomments-4/issues/28#issuecomment-974452091_

### PR DESCRIPTION
**Pull request by Globulopolis**

### CODE REVIEW

**Comment by exstreme** [comment]
Uninstall and drop tables, then install fresh version.
There is no comments form in any category.
image
There is no jcomments plugins installed, something went wrong(

**Comment by exstreme** [comment]
And by default disabled all acl except SuperUsers

**Comment by Globulopolis** [comment]
> Uninstall and drop tables, then install fresh version. There is no comments form in any category. image There is no jcomments plugins installed, something went wrong(

Component must be installed as package.

**Comment by exstreme** [comment]
image
as SuperUser when comment(

**Comment by Globulopolis** [comment]
> 

What's this?

**Comment by exstreme** [comment]
https://github.com/exstreme/Jcomments-4/issues/29 still incorrect

**Comment by Globulopolis** [comment]
> #29 still incorrect

Fixed in https://github.com/exstreme/Jcomments-4/pull/31

**Pull request merged**
