### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by Globulopolis**
This PR finished changes in https://github.com/exstreme/Jcomments-4/pull/13
Remove default.settings.sql as it's not used anymore.
Update component install xml according to latest changes.
Update jcomments plugins.
Complete new feed class.
Fixed bug in object model.

### CODE REVIEW

**Comment by exstreme** [comment]
Bugs:
-JInstaller: :Install: Файла не существует: C:\OpenServer\domains\joomla.test\tmp\install_617c6ddcd50f7\site\router.php.
- Why rollback jcomments.xml file?
- probably problems with db installation

**Comment by exstreme** [comment]
Notice: Undefined index: ru-RU in C:\OpenServer\domains\joomla.test\components\com_jcomments\classes\text.php on line 293

Notice: Trying to get property 'message_policy_whocancomment' of non-object in C:\OpenServer\domains\joomla.test\components\com_jcomments\classes\text.php on line 293

**Comment by Globulopolis** [comment]
> 
> 
> Bugs: -JInstaller: :Install: Файла не существует: C:\OpenServer\domains\joomla.test\tmp\install_617c6ddcd50f7\site\router.php.
> 
>     * Why rollback jcomments.xml file?
> 
>     * probably problems with db installation

router.php isn't working correctly.

**Comment by Globulopolis** [comment]
> 
> 
> Notice: Undefined index: ru-RU in C:\OpenServer\domains\joomla.test\components\com_jcomments\classes\text.php on line 293
> 
> Notice: Trying to get property 'message_policy_whocancomment' of non-object in C:\OpenServer\domains\joomla.test\components\com_jcomments\classes\text.php on line 293

In jcomments settings go to `Messages` tab, add appropriate messages for all content languages. Save settings, test and tell me result.

**Comment by exstreme** [comment]
image

**Comment by exstreme** [comment]
> > Bugs: -JInstaller: :Install: Файла не существует: C:\OpenServer\domains\joomla.test\tmp\install_617c6ddcd50f7\site\router.php.
> > ```
> > * Why rollback jcomments.xml file?
> > 
> > * probably problems with db installation
> > ```
> 
> router.php isn't working correctly.

The biggest problem is rolling back edits that were made in other commits. It turns out that by adding new functionality, you remove other people's edits. Therefore, I ask you to be more careful with merges, I saw this in version 3 as well, I just noticed late that my edits were overwritten.

**Comment by Globulopolis** [comment]
> The biggest problem is rolling back edits that were made in other commits. It turns out that by adding new functionality, you remove other people's edits. Therefore, I ask you to be more careful with merges, I saw this in version 3 as well, I just noticed late that my edits were overwritten.

Sorry for that, but sometimes github not showing up  changes correctly.

**Comment by Globulopolis** [comment]
> 
> 
> image

Add messages for **each** content language.

**Comment by exstreme** [comment]
> > The biggest problem is rolling back edits that were made in other commits. It turns out that by adding new functionality, you remove other people's edits. Therefore, I ask you to be more careful with merges, I saw this in version 3 as well, I just noticed late that my edits were overwritten.
> 
> Sorry for that, but sometimes github not showing up changes correctly.

Did you first pull changes from repository before create PR?

**Comment by exstreme** [comment]
hmmm, still bad(
Table 'joomla.q8nq3_jcomments_settings' doesn't exist
Joomla\CMS\Filesystem\Folder::delete: Путь ведет не к каталогу: C:\OpenServer\domains\joomla.test\components\com_jcomments\languages.
×
danger
Ошибка установки компонента.

**Comment by Globulopolis** [comment]
> 
> 
> > > The biggest problem is rolling back edits that were made in other commits. It turns out that by adding new functionality, you remove other people's edits. Therefore, I ask you to be more careful with merges, I saw this in version 3 as well, I just noticed late that my edits were overwritten.
> > 
> > 
> > Sorry for that, but sometimes github not showing up changes correctly.
> 
> Did you first pull changes from repository before create PR?

I'm always fetch upstream before create PR.

**Pull request merged**
