### PR TITLE
Fixes for prev. PR

### PR DESCRIPTION
**Pull request by Globulopolis**
Fixed https://github.com/exstreme/Jcomments-4/pull/22#issuecomment-960043851
Fixed https://github.com/exstreme/Jcomments-4/pull/22#issuecomment-960058521
Fixed https://github.com/exstreme/Jcomments-4/pull/22#issuecomment-960062084

### CODE REVIEW

**Comment by exstreme** [comment]
I look at the commits and see the addition of conditions ala $ user-> get ('isRoot').
In my opinion, it is completely incorrect to do this, it resembles a logical error, well, in the most extreme case, it should be in another place.

**Comment by Globulopolis** [comment]
You suggestions how to check for super user?

**Comment by exstreme** [comment]
image
still don't working

**Comment by exstreme** [comment]
> Your suggestions how to check for super user?

ACL Do not display captcha
enabled by supersusers
disabled by guests

ACL can comment
enabled by supersusers
enabled by guests

ACL autopublish comments
enabled by supersusers
disabled by guests

etc

**Comment by exstreme** [comment]
This should work at the permissions level, not at the code level in some file.

**Comment by Globulopolis** [comment]
> image
> still don't working

Cannot understand why... Will check it again tomorrow.

**Comment by exstreme** [comment]
image

3 comments can I publish without refreshing captcha

**Comment by Globulopolis** [comment]
> 
> 
> image
> 
> 3 comments can I publish without refreshing captcha
Did you update you local copy from repo? Looks like something is missing.

**Comment by Globulopolis** [comment]
>  still don't working

Under what user?

**Comment by exstreme** [comment]
> > 3 comments can I publish without refreshing captcha
> 
> Did you update you local copy from repo? Looks like something is missing.

It was my fail, updated local copy and all works fine

**Pull request merged**
