### PR TITLE
Updates

### LINKED ISSUE #24: Removing Jcomments leads to a crash of the site
Failed opening required '/components/com_jcomments/helpers/content.php'

Plugins are removed incorrectly

### LINKED ISSUE #25: error messages are not displayed
Errors and warnings

### LINKED ISSUE #26: ACL missleading
We don't need using isRoot() in the code

### LINKED ISSUE #27: Problem with installation
image

cannot reproduce this problem, need more information

### PR DESCRIPTION
**Pull request by Globulopolis**
Added options to display comment title(not input).
Added Gravatar options.
Added logging in critical places.
Kcaptcha color in options is now color picker.
Change installation process. Now it's package.
Changed. Feed class moved to View class.
Changed. Temlates splitted to layouts and support BS5
Fixed Gravatar default image displaying.
Fixed message_terms_of_use. Now it's displayed when needed.
Fixed default access rules.
Fixed displaying Reset button in form.
Fixed #26
Fixed #25
Fixed #24
Fixed #27
Removed word_maxlength because it broking words. Now words break via CSS. Except Arabic.
Removed all frontend languages except Russian, English because they outdated and need to be updated.
Removed search plugin because J4 did not have this group.
Removed version.php. We using component manifest xml file.
Removed unused rules in CSS.
Removed plugins.zip from installer. Installer just copy files to folder.
Update plugins xml.

### CODE REVIEW

**Comment by exstreme** [comment]
Nice work, as always, acl problems:
image
Guest with enabled autopublish

**Comment by exstreme** [comment]
image
As registered array, as guest string 2,9

**Comment by exstreme** [comment]
image
image
By registered

**Comment by exstreme** [comment]
image
image

Button "Ban IP" can't understand is working or no

**Comment by exstreme** [comment]
image
Seems like no

**Comment by Globulopolis** [comment]
> acl problems:  Guest with enabled autopublish

Update you ACL in component settings.

**Comment by Globulopolis** [comment]
> As registered array, as guest string 2,9

Cannot confirm. Tested under super user, registered and guest - always array.

**Comment by Globulopolis** [comment]
> By registered

I think there's a problem while save ACL via component, not via com_config.

**Comment by Globulopolis** [comment]
> image image
> 
> Button "Ban IP" can't understand is working or no

On the first screenshot buttons is the same as in admin panel. Check it.
Ban IP button at the right, after IP. And you cannot ban own IP.

**Pull request merged**
